# Generated by Django 4.2.1 on 2023-05-12 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrintFac', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['payment_date']},
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploaded_at',
        ),
    ]
