# Generated by Django 4.2.1 on 2023-05-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrintFac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='email',
            field=models.EmailField(help_text='Please Enter Email for payment confirmation', max_length=50),
        ),
    ]
