# Generated by Django 4.2.1 on 2023-05-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrintFac', '0003_document_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='anshul', max_length=50),
            preserve_default=False,
        ),
    ]
